# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb233b9b0d6c968a904651d119fc8d4d"
name = "JSlabs AI Chat"
handle = "jslabs-ai-chat"
application_url = "https://localhost:3458"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [ "https://localhost:3458/auth/callback" ]

[pos]
embedded = false

[mcp.customer_authentication]
redirect_uris = [
  "https://localhost:3458/auth/callback"
]
